### ISSUE TITLE
Error en reportfn2date

### ISSUE THREAD

**Issue by pr0nstar** [mauforonda/covid19-bolivia-udape#2]
El script falla al intentar actualizar los datos desde udape:
![image](https://user-images.githubusercontent.com/64463227/147956882-21ce3836-f602-4902-8090-3e3f2f7e579c.png)
El regex que parsea la fecha '([0-9]*_[0-9]*_[0-9]*21)' solo funcionana para el 2021
Cambiando
`match = re.findall('([0-9]*_[0-9]*_[0-9]*21)', reportfn)[0]`
por
`match = re.findall('([0-9]*_[0-9]*_[0-9]*2[1-3]{1})', fn)[0]`
corrige el problema.

**Comment by mauforonda** [comment]
Gracias! [arreglado](https://github.com/mauforonda/covid19-bolivia-udape/commit/a0fa70cf44c0cd0b4e7a2bce4476033c0b57c0f7) :balloon:
